// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJC3HMgk7bwNrCpzXD7aMcMZ_dixVmtlY',
    appId: '1:29716615825:web:bc8c103fec68c2ee106530',
    messagingSenderId: '29716615825',
    projectId: 'flutter-assignment-1f04a',
    authDomain: 'flutter-assignment-1f04a.firebaseapp.com',
    storageBucket: 'flutter-assignment-1f04a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADdcTDKetRcQKV-cl74JHb1hLg8C89B_g',
    appId: '1:29716615825:android:83e5e9f2c67acd95106530',
    messagingSenderId: '29716615825',
    projectId: 'flutter-assignment-1f04a',
    storageBucket: 'flutter-assignment-1f04a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAarr23_LahiVLWmzJ274C4gaEKjd80X-Q',
    appId: '1:29716615825:ios:35089b6b588259d3106530',
    messagingSenderId: '29716615825',
    projectId: 'flutter-assignment-1f04a',
    storageBucket: 'flutter-assignment-1f04a.appspot.com',
    iosClientId: '29716615825-mn2aejcestqmh2bri91qfbd30kkr4f70.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAarr23_LahiVLWmzJ274C4gaEKjd80X-Q',
    appId: '1:29716615825:ios:35089b6b588259d3106530',
    messagingSenderId: '29716615825',
    projectId: 'flutter-assignment-1f04a',
    storageBucket: 'flutter-assignment-1f04a.appspot.com',
    iosClientId: '29716615825-mn2aejcestqmh2bri91qfbd30kkr4f70.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment',
  );
}
